# Generated by cucumber-sinatra. (2015-05-11 11:30:53 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/movies_around_me.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = MoviesAroundMe

class MoviesAroundMeWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  MoviesAroundMeWorld.new
end
